/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_define_window (void);
GtkWidget* create_theme_window (void);
GtkWidget* create_computer_window (void);
GtkWidget* create_select_window (void);
GtkWidget* create_network_window (void);
GtkWidget* create_about_window (void);
GtkWidget* create_tips_window (void);
GtkWidget* create_human_window (void);
